:concurrency: 1 # 并发数
:pidfile: tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log # 输出的日志地址
:queues:
- time # 写在队列参数中的, 表示让 sidekiq 处理这个 queue

development:
:concurrency: 1
staging:
:concurrency: 1
production:
:concurrency: 1
